//CREATE ARRAY OF IMAGES AND HAVE IT BE FOUND WITH STING.TOLOWER AND REMOVE SPACES
//IMAGES{benchpress: require("../assets/WorkoutPics/SumoDeadlift.png"),deadlift: require("../assets/WorkoutPics/SumoDeadlift.png"),}
//workoutName.toLowerCase().replace(/\s+/g, "");
export const catdata = [
  {
    name: "All Workouts",
    workouts: [
      //Chest
      { workoutName: "Barbell Bench Press", set: 0, reps: 0, weight: 0 },
      { workoutName: "Dumbbell Bench Press", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Dumbbell bench", set: 0, reps: 0, weight: 0 },
      { workoutName: "PushUps", set: 0, reps: 0, weight: 0 },
      { workoutName: "Dumbell Chest Fly", set: 0, reps: 0, weight: 0 },
      { workoutName: "Decline Machine Press", set: 0, reps: 0, weight: 0 },
      { workoutName: "Cable Fly", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Cable Fly", set: 0, reps: 0, weight: 0 },

      //back
      { workoutName: "DeadLift", set: 0, reps: 0, weight: 0 },
      { workoutName: "PullUp", set: 0, reps: 0, weight: 0 },
      { workoutName: "Bent Over Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Chest Supported Row ", set: 0, reps: 0, weight: 0 },
      { workoutName: "Lat Pulldown", set: 0, reps: 0, weight: 0 },
      { workoutName: "Neutral Grip Pulldown", set: 0, reps: 0, weight: 0 },
      { workoutName: "Seated Cable Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Cable Rope Pullover", set: 0, reps: 0, weight: 0 },
      { workoutName: "V Bar Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "T Bar Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Wide Back Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Single Arm Dumbbell Row", set: 0, reps: 0, weight: 0 },

      //shoulders
      { workoutName: "Barbell Overhead Press", set: 0, reps: 0, weight: 0 },
      {
        workoutName: "Seated Dumbbell Shoulder Press",
        set: 0,
        reps: 0,
        weight: 0,
      },
      { workoutName: "Dumbbell Lateral Raise", set: 0, reps: 0, weight: 0 },
      { workoutName: "Cable Lateral Raise ", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Front Raise", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Upright Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Reverse Dumbbell Flyes", set: 0, reps: 0, weight: 0 },
      { workoutName: "Face Pull", set: 0, reps: 0, weight: 0 },

      //Biceps
      { workoutName: "Dumbbell Bicep Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Hammer Curls", set: 0, reps: 0, weight: 0 },
      { workoutName: "Ez Bar Curls", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Dumbbell Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Spider Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Preacher Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Zottman Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Curl", set: 0, reps: 0, weight: 0 },

      //Triceps
      { workoutName: "Dumbbell Skullcrusher", set: 0, reps: 0, weight: 0 },
      { workoutName: "Ez Bar Skullcrusher", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Skullcrusher", set: 0, reps: 0, weight: 0 },
      { workoutName: "Rope Tricep Pushdown", set: 0, reps: 0, weight: 0 },
      { workoutName: "Tricep Pushdown", set: 0, reps: 0, weight: 0 },
      {
        workoutName: "Rope Overhead Tricep Extension",
        set: 0,
        reps: 0,
        weight: 0,
      },
      { workoutName: "Tricep Kickback", set: 0, reps: 0, weight: 0 },

      //legs
      { workoutName: "Dumbbell Squat", set: 0, reps: 0, weight: 0 },
      { workoutName: "Leg Extension", set: 0, reps: 0, weight: 0 },
      { workoutName: "Goblet Squat", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Squat", set: 0, reps: 0, weight: 0 },
      { workoutName: "Hamstring Curls", set: 0, reps: 0, weight: 0 },
      { workoutName: "Romanian Deadlift", set: 0, reps: 0, weight: 0 },
      { workoutName: "Hip Thrusts", set: 0, reps: 0, weight: 0 },
      { workoutName: "Wide Pulse Squats", set: 0, reps: 0, weight: 0 },

      //cal
      // { workoutName: "Dips", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Assisted Push Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Assisted Pull Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Assisted Dips", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Wallsit", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Sit Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Planks", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Crunches", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Leg Raise", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Russian Twists", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Side Planks", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Knee Crunch", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Flutter Kicks", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Pulse Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Toe Taps", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Six Inch Hold", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Wipers", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Bicycle Crunch", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Kneeling Push Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Decline Push Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Incline Push Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Wide Grip Push Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Triangle Push Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Bench Dips", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Chin Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Jump Squats", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Muscle Ups", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Back Lever", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Full Lever", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Human Flag", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Planche", set: 0, reps: 0, weight: 0 },

      //cardio
      { workoutName: "Jumping Jacks", set: 0, reps: 0, weight: 0 },
      { workoutName: "Mountain Climber", set: 0, reps: 0, weight: 0 },
      { workoutName: "Burpees", set: 0, reps: 0, weight: 0 },
      { workoutName: "Knee To Elbow", set: 0, reps: 0, weight: 0 },
      { workoutName: "Pacer Steps", set: 0, reps: 0, weight: 0 },
      { workoutName: "Lunges", set: 0, reps: 0, weight: 0 },
      { workoutName: "High Knees", set: 0, reps: 0, weight: 0 },
      { workoutName: "Treadmill", set: 0, reps: 0, weight: 0 },
      { workoutName: "Elliptical", set: 0, reps: 0, weight: 0 },
      { workoutName: "Bicycle", set: 0, reps: 0, weight: 0 },
      { workoutName: "Stairmaster", set: 0, reps: 0, weight: 0 },
    ],
  },
  {
    name: "Chest",
    workouts: [
      { workoutName: "Barbell Bench Press", set: 0, reps: 0, weight: 0 },
      { workoutName: "Dumbbell Bench Press", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Dumbbell bench", set: 0, reps: 0, weight: 0 },
      { workoutName: "PushUps", set: 0, reps: 0, weight: 0 },
      { workoutName: "Dumbell Chest Fly", set: 0, reps: 0, weight: 0 },
      { workoutName: "Decline Machine Press", set: 0, reps: 0, weight: 0 },
      { workoutName: "Cable Fly", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Cable Fly", set: 0, reps: 0, weight: 0 },
    ],
  },
  {
    name: "Back",
    workouts: [
      { workoutName: "DeadLift", set: 0, reps: 0, weight: 0 },
      { workoutName: "PullUp", set: 0, reps: 0, weight: 0 },
      { workoutName: "Bent Over Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Chest Supported Row ", set: 0, reps: 0, weight: 0 },
      { workoutName: "Lat Pulldown", set: 0, reps: 0, weight: 0 },
      { workoutName: "Neutral Grip Pulldown", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Seated Cable Row", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Cable Rope Pullover", set: 0, reps: 0, weight: 0 },
      // { workoutName: "V Bar Row", set: 0, reps: 0, weight: 0 },
      // { workoutName: "T Bar Row", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Wide Back Row", set: 0, reps: 0, weight: 0 },
      // { workoutName: "Single Arm Dumbbell Row", set: 0, reps: 0, weight: 0 },
    ],
  },
  {
    name: "Shoulders",
    workouts: [
      { workoutName: "Barbell Overhead Press", set: 0, reps: 0, weight: 0 },
      {
        workoutName: "Seated Dumbbell Shoulder Press",
        set: 0,
        reps: 0,
        weight: 0,
      },
      { workoutName: "Dumbbell Lateral Raise", set: 0, reps: 0, weight: 0 },
      { workoutName: "Cable Lateral Raise ", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Front Raise", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Upright Row", set: 0, reps: 0, weight: 0 },
      { workoutName: "Reverse Dumbbell Flyes", set: 0, reps: 0, weight: 0 },
      { workoutName: "Face Pull", set: 0, reps: 0, weight: 0 },
    ],
  },

  {
    name: "Biceps",
    workouts: [
      { workoutName: "Dumbbell Bicep Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Hammer Curls", set: 0, reps: 0, weight: 0 },
      { workoutName: "Ez Bar Curls", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Dumbbell Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Spider Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Preacher Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Zottman Curl", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Curl", set: 0, reps: 0, weight: 0 },
    ],
  },

  {
    name: "Triceps",
    workouts: [
      { workoutName: "Dumbbell Skullcrusher", set: 0, reps: 0, weight: 0 },
      { workoutName: "Ez Bar Skullcrusher", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Skullcrusher", set: 0, reps: 0, weight: 0 },
      { workoutName: "Rope Tricep Pushdown", set: 0, reps: 0, weight: 0 },
      { workoutName: "Tricep Pushdown", set: 0, reps: 0, weight: 0 },
      {
        workoutName: "Rope Overhead Tricep Extension",
        set: 0,
        reps: 0,
        weight: 0,
      },
      { workoutName: "Tricep Kickback", set: 0, reps: 0, weight: 0 },
    ],
  },

  {
    name: "Legs",
    workouts: [
      { workoutName: "Dumbbell Squat", set: 0, reps: 0, weight: 0 },
      { workoutName: "Leg Extension", set: 0, reps: 0, weight: 0 },
      { workoutName: "Goblet Squat", set: 0, reps: 0, weight: 0 },
      { workoutName: "Barbell Squat", set: 0, reps: 0, weight: 0 },
      { workoutName: "Hamstring Curls", set: 0, reps: 0, weight: 0 },
      { workoutName: "Romanian Deadlift", set: 0, reps: 0, weight: 0 },
      { workoutName: "Hip Thrusts", set: 0, reps: 0, weight: 0 },
      { workoutName: "Wide Pulse Squats", set: 0, reps: 0, weight: 0 },
    ],
  },
  {
    name: "Calestetics",
    workouts: [
      { workoutName: "Dips", set: 0, reps: 0, weight: 0 },
      { workoutName: "Assisted Push Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Assisted Pull Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Assisted Dips", set: 0, reps: 0, weight: 0 },
      { workoutName: "Wallsit", set: 0, reps: 0, weight: 0 },
      { workoutName: "Sit Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Planks", set: 0, reps: 0, weight: 0 },
      { workoutName: "Crunches", set: 0, reps: 0, weight: 0 },
      { workoutName: "Leg Raise", set: 0, reps: 0, weight: 0 },
      { workoutName: "Russian Twists", set: 0, reps: 0, weight: 0 },
      { workoutName: "Side Planks", set: 0, reps: 0, weight: 0 },
      { workoutName: "Knee Crunch", set: 0, reps: 0, weight: 0 },
      { workoutName: "Flutter Kicks", set: 0, reps: 0, weight: 0 },
      { workoutName: "Pulse Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Toe Taps", set: 0, reps: 0, weight: 0 },
      { workoutName: "Six Inch Hold", set: 0, reps: 0, weight: 0 },
      { workoutName: "Wipers", set: 0, reps: 0, weight: 0 },
      { workoutName: "Bicycle Crunch", set: 0, reps: 0, weight: 0 },
      { workoutName: "Kneeling Push Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Decline Push Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Incline Push Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Wide Grip Push Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Triangle Push Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Bench Dips", set: 0, reps: 0, weight: 0 },
      { workoutName: "Chin Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Jump Squats", set: 0, reps: 0, weight: 0 },
      { workoutName: "Muscle Ups", set: 0, reps: 0, weight: 0 },
      { workoutName: "Back Lever", set: 0, reps: 0, weight: 0 },
      { workoutName: "Full Lever", set: 0, reps: 0, weight: 0 },
      { workoutName: "Human Flag", set: 0, reps: 0, weight: 0 },
      { workoutName: "Planche", set: 0, reps: 0, weight: 0 },
    ],
  },
  {
    name: "Cardio",
    workouts: [
      { workoutName: "Jumping Jacks", set: 0, reps: 0, weight: 0 },
      { workoutName: "Mountain Climber", set: 0, reps: 0, weight: 0 },
      { workoutName: "Burpees", set: 0, reps: 0, weight: 0 },
      { workoutName: "Knee To Elbow", set: 0, reps: 0, weight: 0 },
      { workoutName: "Pacer Steps", set: 0, reps: 0, weight: 0 },
      { workoutName: "Lunges", set: 0, reps: 0, weight: 0 },
      { workoutName: "High Knees", set: 0, reps: 0, weight: 0 },
      { workoutName: "Treadmill", set: 0, reps: 0, weight: 0 },
      { workoutName: "Elliptical", set: 0, reps: 0, weight: 0 },
      { workoutName: "Bicycle", set: 0, reps: 0, weight: 0 },
      { workoutName: "Stairmaster", set: 0, reps: 0, weight: 0 },
    ],
  },
];
